### PR TITLE
Slimming down docker image

### PR DESCRIPTION
**Pull request by socketbox**
Going with slim-buster as the base (saves us almost 500MB), though it requires installing `gcc` (for the `psycopg2` build).

Removing `POETRY_VERSION` as an arg since it is hardcoded in the dockerfile and the included shasum would have to be verified if the version was changed regardless.

`ADD` a better alternative than `wget`

### CODE REVIEW

**Review by easherma — COMMENTED** [review]
[libjpeg and zlib are two other libraries that would need to be installed](https://docs.wagtail.io/en/stable/getting_started/index.html#dependencies-needed-for-installation) in order for image renditions to work. 

There may be some other things in the Debian image that are also useful (psql client maybe), but I'd have to check.

Two other questions: 
* Is it possible we'd be trading image size for extra build time? 
* When are you expecting the production container will be rebuilt? Will it be able to take advantage of Docker's caching?

**Comment by socketbox** [comment]
> libjpeg and zlib are two other libraries that would need to be installed
Good to know. `zlib` comes free of charge, but libjpeg will need to be explicitly installed. Adding that in a commit now.

> Two other questions:
> 
> * Is it possible we'd be trading image size for extra build time?
Are you referring to the `psycopg2` dependency? It's built regardless of the base image used.

> * When are you expecting the production container will be rebuilt? 
Anytime that the underlying files or the commands in the Dockerfile change. 

> * Will it be able to take advantage of Docker's caching?
Yes, caching will be realized regardless of the context (local or remote), provided that changes have been built previously.

**Comment by easherma** [comment]
@socketbox have you done any testing off this branch to see if everything builds and if the app still runs correctly? I'm working on figuring out a full list of dependencies we may need for production that are in the debian image but _not_ in slim (TL;DR it's probably not a huge list but more than just libjpeg)

**Comment by socketbox** [comment]
@easherma I've run the image locally, but don't have a good rubric for testing, other than visual inspection of the site (in its current stage of development) and the administrative pages.

Do you have any suggestions for testing? I'm game for pretty much anything and would be willing to post screenshots, if that would help.

**Comment by easherma** [comment]
I don't have a good plan for testing other than 'see if anything breaks'. For that reason it might be better to split up the prep for production deployment from sliming down the image, just so we reduce the number of potential sources of issues until something is live. How does that sound?

**Comment by socketbox** [comment]
Sounds good. I'll keep the branch warm and waiting for a subsequent, post-production iteration.

**Pull request closed without merging**
